name: scrape data
run-name: ${{ github.actor }} is scraping and uploading data to s3
on:
  workflow_dispatch:
  schedule:
    - cron: "*/6 * * * *"

jobs:
  scrape-data:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
      - name: install dependencies
         run: npm ci
      - name: scrape data
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
        run: |
          node index.js
